### PR TITLE
Updated tags to use color images from https://shields.io

### PR DESCRIPTION
**Pull request by mshirlaw**
Examples of how this might look have been included below. Having gone through this process I think it might be nice to also have a consistent color scheme (something that makes sense for the tag) so that tags can be added easily etc. Let me know what you think @jchiatt 

breakfast budget meat

sweets sugar-alternative sweeteners

cheese

snack budget meat

vegetarian

### CODE REVIEW

**Comment by jchiatt** [comment]
Hey @mshirlaw this is great! One small change: let’s add the tags to the top of the file right under the doc title

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mshirlaw** [comment]
Sure thing will do

**Comment by mshirlaw** [comment]
Ok I changed it up and made sure there was an appropriate title in each case. I also fixed a minor typo. Let me know if you are ok with these changes now @jchiatt

**Comment by jchiatt** [comment]
@mshirlaw  LGTM! Merging!

**Pull request merged**
